### ISSUE TITLE
Title breaking with big name

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/electric#11]
I created a project called "API Style guide" and the container for the project name breaks.

<img width="282" alt="screen shot 2017-01-25 at 10 22 26 am" src="https://cloud.githubusercontent.com/assets/301291/22303485/473b6b9a-e2e8-11e6-818a-a801ad7aba6d.png">

**Comment by zenorocha** [comment]
Yes, we need to fix that too. Can you move this issue to the generator repo too?

**Comment by pragmaticivan** [comment]
Is this template inside the generator?

**Comment by zenorocha** [comment]
Yes
