### ISSUE TITLE
New autocomplete instances being created after navigation

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/electric#17]
Steps to reproduce:
1. Go to a docs page
2. Navigate between other pages
3. See on devtools how many autocompletes have been created

<img width="1439" alt="screen shot 2017-02-10 at 5 42 21 pm" src="https://cloud.githubusercontent.com/assets/398893/22850037/5d9b8578-efb8-11e6-9682-989376e9990c.png">

**Comment by Robert-Frampton** [comment]
Fixed with https://github.com/wedeploy/electric-base-components/commit/25ba613c31544945f007a8b38d69e6e7df191399
