### ISSUE TITLE
Create our own CLI

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/electric#3]
Investigate the idea of having our own CLI instead of relying on Gulp and Yeoman.

> See https://github.com/metal/metal-cli as a reference.

**Comment by julien** [comment]
Hi @zenorocha,

I'd be happy to help with the task, is there anything I should know before starting? 
Thanks

**Comment by Robert-Frampton** [comment]
Hey @julien 

We might not want to start on this just yet, since there are more changes coming soon.

**Comment by julien** [comment]
Ok.

**Comment by Robert-Frampton** [comment]
https://github.com/wedeploy/electric-cli
