### ISSUE TITLE
Allow numbers in blog post file names

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/electric#31]
When I tried to add a new blog post markdown file named `liferay-blog-post-2017.md`, it threw me an error `Cannot read property '1' of null`. Once I removed '2017' from the file name, it compiled fine.

**Comment by Robert-Frampton** [comment]
I think it's using the file name to create the soy namespace, but I think soy doesn't support numbers in namespaces, so we'll have to figure out a different way of generating the namespace for markdown files.

**Comment by Robert-Frampton** [comment]
82799fe2df82db24136233c50ed02a90ec562dfa
